FROM getmeili/meilisearch:v1.12

# Expose Meilisearch default port
EXPOSE 7700

# Render uses PORT env variable
ENV MEILI_HTTP_ADDR=0.0.0.0:${PORT:-7700}
ENV MEILI_DB_PATH=/data.ms
ENV MEILI_ENV=production
ENV MEILI_NO_ANALYTICS=true
# Limit indexing memory to avoid OOM on 512MB plans
ENV MEILI_MAX_INDEXING_MEMORY=200mb

# Run Meilisearch
CMD meilisearch --http-addr "0.0.0.0:${PORT:-7700}"
